name: gimmenow_demo
description: GimmeNow demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  amplify_flutter: ^0.2.0
  amplify_auth_cognito: ^0.2.0
  amplify_datastore: ^0.2.0
  amplify_analytics_pinpoint: ^0.2.0
  font_awesome_flutter: ^9.0.0
  amplify_storage_s3: ^0.2.0
  amplify_api: ^0.2.0
  intl: ^0.17.0
  image_picker: ^0.8.0+3
  uuid: ^3.0.4
  transparent_image: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/facebook-logo.png
    - images/google-logo.png
    - images/amazon-logo.png
    - images/applogo.png
    - images/aws.png
    - images/profile.png
    - images/profile_image.png
